### ISSUE TITLE
[DISCUSS] Guideline change: Icon or button

### ISSUE THREAD

**Issue by szabosteve** [elastic/tech-writing-guidelines#25]
# Proposed changes

## Icon or button

* If there is no text next to an actionable, visual symbol, it's an icon.
* If there is text next to an actionable visual symbol, it's a button.
* An actionable piece of text without a visual symbol is either a link or a button.
* In the docs, refer to an icon with its symbol. For example:
  * **From the Action menu (...), select Delete job.** In this example, the (...) represents the Action menu icon.

(You can also find the proposed change on the [ponderisms](https://docs.elastic.dev/guide/ponderisms#icon-or-button) page.)

Please ask your questions/share your opinion below.

**Comment by jmikell821** [comment]
Proposed changes LGTM. Thanks @szabosteve! Do I close the issue out once approved, do we open a PR -- what's the next step?

**Comment by szabosteve** [comment]
@jmikell821 I think we should wait until the discussion period ends (May 24), so people have time to make their point. Details can be found in this PR: https://github.com/elastic/tech-writing-guidelines/pull/27 It'll be merged soon. Last week on the bi-weekly, we discussed that you'll be the one who declares if we have a consensus. :) This is why I added you to the ticket. 

Once the above-mentioned PR is merged, I let the other writers know about the updated page, so they can share their opinions here if they want. If there is no objection regarding the proposed changes, I'll close this issue and update the guidelines. If there is a debate, we'll see the results and act accordingly. On your side, there is nothing more to do at the moment.

(Sorry for pinging you on this ticket before the PR got merged and without further explanation. I thought I can merge the PR and send the updated page to you, so you could have context but it got delayed because of a failing CI job. Thanks for your understanding!)

**Comment by dedemorton** [comment]
Can you show examples of the different types of controls as they appear in the Kibana UI? That might help clarify exactly what you are proposing.

Also the issue needs to include the proposal for historical reasons. Otherwise, you are likely to have folks asking for the same thing over and over again. It's better if you can point them to the issue where the discussion takes place. Also makes it easier to review the proposal without jumping back and forth between the ponderisms page and the issue.

**Comment by szabosteve** [comment]
@dedemorton You are right! Thanks for the advice! I added the proposed changes to the root comment (and will do the same on the other issue). I'll add a reminder sentence about it to the template on the page, too, so folks won't forget to include the proposed changes in the issue when they open a proposal.

> Can you show examples of the different types of controls as they appear in the Kibana UI? That might help clarify exactly what you are proposing.

I would defer to @jmikell821 in this one as this is her proposal (I opened the issue and published the proposed changes on the Ponderisms page only to initiate some kind of process). She might have some good examples in her mind and I'm sure her argument would be more accurate than mine.

**Comment by jmikell821** [comment]
Hey @dedemorton - here's a good example of the Alerts page in Elastic Security. 

![2022-05-18_12-51-44](https://user-images.githubusercontent.com/57149392/169098755-bc48e4f3-51b6-46a3-919e-158c5933d93a.png)

1) Button
2) Link 
3) Icon

Now #3 is interesting because at first glance there is no text next to the visual symbol, but when you hover over it, a pop-up of the name appears. I'd be inclined still to call this more of an icon based on the description above. 

Thoughts?

**Comment by dedemorton** [comment]
@jmikell821 I agree. 3 is an icon. To me, a button looks like a button. :-) Most buttons have text on them. 

I think it would be a good idea to look at Kibana in a screen reader to figure out what kind of control is announced for each of these UI controls. Otherwise our docs could be disorienting to folks who are visually impaired. It's been awhile since I've done extensive accessibility testing, but I think that most (maybe all) screen readers announce UI controls so users know how to interact with them.

**Comment by dedemorton** [comment]
Just did a quick test with VoiceOver, and it calls a lot of stuff buttons. Should we take this into consideration in our guidelines?

**Comment by jmikell821** [comment]
> Just did a quick test with VoiceOver, and it calls a lot of stuff buttons. Should we take this into consideration in our guidelines?

@dedemorton I'm not surprised it calls a lot of UI elements buttons, but I think a distinction between icon and button is important here. But we can definitely take it into consideration. Please feel free to share what the test results say. 👀

**Comment by dedemorton** [comment]
I think it would be good to test on Jaws, too, but pretty much every icon and some links are announced as buttons. TBH I don't know how VoiceOver determines the UI control type. I guess we could go with "icon" for now and revisit this decision later on. If we decide to change it later on, we can probably lint for it and do some global fixes. WDYT?

**Comment by jmikell821** [comment]
@dedemorton that sounds good to me - let's carry on with what's in the proposal for `button` and `icon`. Thanks!

**Comment by szabosteve** [comment]
I raised a PR to add the proposed changes to the guidelines. Thanks for the input on this topic. I close this issue.
https://github.com/elastic/tech-writing-guidelines/pull/42
